# Generated by Django 6.0.1 on 2026-01-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'To do List App', 'verbose_name_plural': 'To do List App List'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateField(),
        ),
    ]
