# Generated by Django 6.0.1 on 2026-02-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Comment App', 'verbose_name_plural': 'Comment App List'},
        ),
    ]
