# Generated by Django 6.0.2 on 2026-02-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userfollowing_user_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('to_user', 'from_user')},
        ),
    ]
